name: 番禺天气推送
on:
  workflow_dispatch:
  schedule:
    # UTC23点 = 北京时间早上7点
    - cron: '0 23 * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install requests

      - name: 运行脚本
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
        run: python weather.py
